import React, { useState, useEffect } from 'react';
import './GitHubCalendar.css';

/**
 * GitHubSnake — Displays the animated snake contribution grid.
 * SVG is generated by GitHub Actions (Platane/snk) in sghani001/sghani001
 * and served from the output branch — already working!
 */
const GitHubSnake = ({ username, theme = 'dark' }) => {
  const [loaded, setLoaded] = useState(false);
  const [imgError, setImgError] = useState(false);

  // Exact URLs matching the output branch in sghani001/sghani001
  const darkSrc = `https://raw.githubusercontent.com/${username}/${username}/output/github-contribution-grid-snake-dark.svg`;
  const lightSrc = `https://raw.githubusercontent.com/${username}/${username}/output/github-contribution-grid-snake.svg`;
  const src = theme === 'dark' ? darkSrc : lightSrc;

  // Reset on theme switch
  useEffect(() => {
    setLoaded(false);
    setImgError(false);
  }, [theme]);

  return (
    <div className="github-snake-root glass-card">
      {/* Header */}
      <div className="github-snake-header">
        <div className="github-snake-title-row">
          <h3 className="github-snake-title">Developer Activity</h3>
        </div>
        <a
          href={`https://github.com/${username}`}
          target="_blank"
          rel="noreferrer"
          className="github-snake-profile-link"
        >
          @{username} ↗
        </a>
      </div>

      {/* Divider */}
      <div className="github-snake-divider" aria-hidden />

      {/* Snake SVG frame */}
      <div className="github-snake-frame">
        {/* Loading shimmer — hidden once loaded */}
        {!loaded && !imgError && (
          <div className="github-snake-loading">
            <span className="github-snake-loading-icon">🐍</span>
            <span className="github-snake-loading-text">Loading snake…</span>
          </div>
        )}

        {!imgError ? (
          <img
            src={src}
            alt={`GitHub contribution snake animation for ${username}`}
            className={`github-snake-svg ${loaded ? 'github-snake-svg--visible' : ''}`}
            onLoad={() => setLoaded(true)}
            onError={() => { setImgError(true); setLoaded(true); }}
          />
        ) : (
          // Fallback to light SVG if dark fails (or vice versa)
          <img
            src={theme === 'dark' ? lightSrc : darkSrc}
            alt={`GitHub contribution snake animation for ${username}`}
            className="github-snake-svg github-snake-svg--visible"
            onError={() => {}}
          />
        )}
      </div>

      {/* Footer */}
      <div className="github-snake-footer">
        <span className="github-snake-legend">
          <span className="github-snake-dot github-snake-dot--empty" />
          No contributions
        </span>
        <span className="github-snake-legend">
          <span className="github-snake-dot github-snake-dot--low" />
          Low
        </span>
        <span className="github-snake-legend">
          <span className="github-snake-dot github-snake-dot--mid" />
          Medium
        </span>
        <span className="github-snake-legend">
          <span className="github-snake-dot github-snake-dot--high" />
          High
        </span>
      </div>
    </div>
  );
};

export default GitHubSnake;
